version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.2"
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.2"
    hostname: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: 192.168.1.5
      ELASTICSEARCH_URL: http://192.168.1.5:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme